[package]
name = "brave-rofi"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
serde_json = "1"
anyhow = "1"
url = "2"
urlencoding = "2.1.2"
